version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - api/.env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  api:
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app/backend
    ports:
      - 8000:8000
    env_file:
      - api/.env
    depends_on:
      - db

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  postgres_data: